### PR TITLE
rollcall added, tweet confirmation message and tidied up spacing

### PR DESCRIPTION
**Pull request by maxhebditch**

### CODE REVIEW

**Comment by maxhebditch** [comment]
Also now added a q-add feature to quote people directly from irc log like so

    !q-add dan

will add dan's last piece of dialogue from the irc log

    !q-add dan 2

will add what dan said two statements back

**Comment by maxhebditch** [comment]
Fixed a bug causing it to crash.

**Comment by maxhebditch** [comment]
Added reading in of famouslastwords script

**Comment by maxhebditch** [comment]
Added ircpopularity script like so

    !ircpopularity dogs cats

only takes two arguements

**Comment by jumblesale** [comment]
:heart:

**Pull request merged**
